language: python
python:
 
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
 - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then python -m unittest discover; fi
 - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi
 - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi
branches:
  only:
    - master