
language: python
sudo: false

python:
 
  - "3.6"

# command to install dependencies
install:
#  - pip install-r requirements.txt
  - docker pull mongo
  - pip install pylint
  - docker build -t bot src/
  - docker run -d --rm -p 27017:27017 --name mongodb mongo
  - docker run -p 80:80 -v ${pwd}/src/:${pwd}/app/ --link mongo --name bot bot

# command to run tests
script:
 - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then python -m unittest discover; fi
 - pylint db.py

branches:
  only:
    - master